### ISSUE TITLE
cpanspec -b CryptX-0.046.tar.gz fails to build RPM on stock el6

### ISSUE THREAD

**Issue by mrdvt92** [DCIT/perl-CryptX#34]
cpanspec will not build RPM out of box.  Something must not be compatible with cpanspec and I'm not familiar enough to know why.  But, this is how I had to modify the cpanspec generated spec file to build an rpm on el6.

Error 1

```
RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/lib64/perl5/vendor_perl/Crypt/AuthEnc.pm
  ...
```
Appears that the package is in the Crypt folder and not the CryptX folder as cpanspec expected.

```
< %{perl_vendorarch}/CryptX*
> %{perl_vendorarch}/Crypt*
```

Error 2

```
RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/lib64/perl5/vendor_perl/Math/BigInt/LTM.pm
```

Appears that Math::BigInt::LTM is provided in this distribution as opposed to in it's own distribution.
```
> %{perl_vendorarch}/Math*
```

perl-Crypt-JWT appears to have passed all of its tests so I'm happy.

**Comment by karel-m** [comment]
What exactly can I do on CryptX side?

The fact that CryptX contains not only the module `CryptX` but also modules `Crypt::*` and `Math::BigInt::LTM` is a feature.

Maybe @dfateyev might have some suggestion here.

**Comment by mrdvt92** [comment]
What I would do is split everything into their own namespace and add the correct dependencies.  Otherwise you could put everything under the CryptX namespace which is not recommend as that is a top level namespace.  With RPMs the migration is simple with the requires and conflicts directives not as easy with cpan.

I would recommend separate distributions for all of these.
CryptX
Math::BigInt::LTM
Crypt::AuthEnc
Crypt::Checksum
Crypt::Cipher
Crypt::Digest
Crypt::KeyDerivation
Crypt::Mac
Crypt::Misc
Crypt::Mode
Crypt::PK
Crypt::PRNG

**Comment by dfateyev** [comment]
I wouldn't say anything about splitting components (whether it worth or not), since the initial topic was a bit different.

As for the cpanspec compliance, actually it produces very basic package spec, which is almost in all cases too far from being proper (and the reason is not the deprecated spec format it produces, but missing dependencies). It's good as a template only, and cannot be accepted "as is" to Fedora, for example. So I wouldn't rely on cpanspec workability at all.

**Comment by dfateyev** [comment]
Little offtopic: I do hope that one day CryptX package will land the Fedora repo (and EPEL, too). Today, it's even easier with Fedora packaging rules relaxation, when lots of stuff can come bundled inside the package, but I would prefer to do it right.
We need to actualize "libtomcrypt" and "libtommath" in Fedora, package "tomsfastmath", and then package CryptX unbundled from libtom components.

**Comment by karel-m** [comment]
Ad splitting to more distribution - it is currently out of question, one jumbo distribution was intentional decision and it is not going to change in foreseeable future.

From what was written it seems to me that it is more a cpanfile's deficiency that it is not able to correctly handle a bit complicated structure of this distribution.

Ad linking with externally supplied libtomcrypt/libtommath - it is just about a patch to  Makefile.PL. Biggest trouble is that CryptX contains some extra ECC related patches that were still not merged to libtomcrypt (but thinks are moving slightly forwards).
