### ISSUE TITLE
Static compile fails with "multiple definition of `rijndael_setup'"

### ISSUE THREAD

**Issue by pRiVi** [DCIT/perl-CryptX#41]
Trying to compile with staticperl(https://metacpan.org/pod/distribution/App-Staticperl/staticperl.pod) on debian jessie failes with the following error, modular compile works (e.g. cpanm), just static compile has problems:

```
/root/.staticperl/perl/lib/auto/Crypt/Rijndael/Rijndael.a(_rijndael.o): In function `rijndael_setup':
/root/.staticperl/cpan/build/Crypt-Rijndael-1.13-0/_rijndael.c:310: multiple definition of `rijndael_setup'
blib/arch/auto/CryptX/CryptX.a(aes.o):/root/.staticperl/cpan/build/CryptX-0.055-2/src/ltc/ciphers/aes/aes.c:127: first defined here
```
**See Full log here: [err.log](https://github.com/DCIT/perl-CryptX/files/1568328/err.log)**

**Comment by karel-m** [comment]
It look like you cannot combine `Crypt:::Rijndael` and `CryptX` (= the distrubution containing `Crypt::Mac::HMAC`) as they both contain `rijndael_setup` function:
* `Crypt-Rijndael-1.13-0/_rijndael.c`
* `CryptX-0.055-2/src/ltc/ciphers/aes/aes.c`

Instead of [Crypt::Rijndael](https://metacpan.org/pod/Crypt::Rijndael) you can use [Crypt::Cipher::AES](https://metacpan.org/pod/Crypt::Cipher::AES) which is part of [CryptX](https://metacpan.org/release/CryptX)
